services:
  - type: web
    name: n8n-creative-kulhad
    env: docker
    dockerfilePath: Dockerfile # We can deploy directly using a Docker image or a simple single-line Dockerfile
    plan: starter
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: 5678
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: NODE_ENV
        value: production
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
      - key: N8N_CORS_ALLOWED_ORIGINS
        value: "*"
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        sync: false
      - key: DB_POSTGRESDB_PORT
        sync: false
      - key: DB_POSTGRESDB_DATABASE
        sync: false
      - key: DB_POSTGRESDB_USER
        sync: false
      - key: DB_POSTGRESDB_PASSWORD
        sync: false
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: false
      - key: DB_POSTGRESDB_SSL_ENABLED
        value: true
      - key: DB_POSTGRESDB_CONNECTION_TIMEOUT
        value: 60000
      - key: N8N_RUNNERS_GRANT_TOKEN_TTL
        value: 120000
      - key: N8N_PYTHON_ENABLED
        value: false
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: WEBHOOK_URL
        value: https://creativekulhad.onrender.com/ # Your hosted Render service URL
    disk:
      name: n8n-storage
      mountPath: /home/node/.n8n
      sizeGB: 1
